---
- hosts: docker
  vars:
      db_volume: mariadb
      wordpress: wordpress
  tasks:
      - name: Deploy MariaDB server
        docker_container:
          image: mariadb
          name: mariadb
          volumes:
            - "{{db_volume}}:/var/lib/mysql"
          env:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: infnet
            MYSQL_DATABASE: db_TP4_TP5
            MYSQL_USER: infnet

      - name: Deploy WordPress
        docker_container:
          image: wordpress
          name: wordpress
          restart_policy: always
          ports:
            - "8080:80"
          links:
            - "{{db_volume}}:/var/lib/mysql"
          volumes:
            - "{{wordpress}}:/var/www/html"
          env:
            MYSQL_PASSWORD: infnet
            MYSQL_DATABASE: db_TP4_TP5
            MYSQL_USER: infnet
            MYSQL_HOST: mariadb

